### ISSUE TITLE
Ladders

### ISSUE THREAD

**Issue by Tyluur** [2011Scape/game#202]
This issue addresses all climbable objects across the world (contain climb right click options).
More specifically:

- Stairs
- Ladders
- Trapdoors

**Comment by Tyluur** [comment]
As of today, the target destination for climbable objects that can be programmatically found has not been completed. Once this is complete, we will have a majority of climbable objects enabled worldwide.

**Comment by Tyluur** [comment]
Code: https://github.com/bridge-io/bridge-rs/blob/029597a98fef084495a5fd9261eb48b48acb9c62/game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/climbable_object.plugin.kts

**Comment by HarleyGilpin** [comment]
I fixed ladder awhile ago, everything should be working now.
