### ISSUE TITLE
uses of vampyre should be vampire

### ISSUE THREAD

**Issue by ultraviolet-jordan** [2011Scape/game#505]
## Current Behavior
- there be `vampyre`

## Expected Behavior
- to be `vampire`

## Steps to Reproduce the Problem

  1. Login the game.
  2. Engage with quest content.
  3. Decide to do Vampire Slayer.
  4. Witness uses of `vampyre`

**Comment by ultraviolet-jordan** [comment]
@HarleyGilpin It should be `vampire` though if this is an emulation. OSRS updated all of their uses from `vampire` to `vampyre` pretty recently if you check the updates.

**Comment by HarleyGilpin** [comment]
> @HarleyGilpin It should be `vampire` though if this is an emulation. OSRS updated all of their uses from `vampire` to `vampyre` pretty recently if you check the updates.

Our target emulation date is October 6th, 2011.

On [31 August](https://runescape.wiki/w/31_August) [2011](https://runescape.wiki/w/2011), all relevant content named 'Vampire' was changed to 'Vampyre', except for this quest. This happened later on [6 September](https://runescape.wiki/w/6_September) 2011.

**Comment by ultraviolet-jordan** [comment]
> > @HarleyGilpin It should be `vampire` though if this is an emulation. OSRS updated all of their uses from `vampire` to `vampyre` pretty recently if you check the updates.
> 
> Our target emulation date is October 6th, 2011.
> 
> On [31 August](https://runescape.wiki/w/31_August) [2011](https://runescape.wiki/w/2011), all relevant content named 'Vampire' was changed to 'Vampyre', except for this quest. This happened later on [6 September](https://runescape.wiki/w/6_September) 2011.

You are correct.
